### ISSUE TITLE
Why is file named `lolcation` instead of `location` ?

### ISSUE THREAD

**Issue by elidoran** [unshiftio/url-parse#10]
The file has that name and the docs say the returned object is that, and the name of the function in the file is that. So, I'm curious why is all.

**Comment by 3rd-Eden** [comment]
Good question. The original idea was to release the file as separate submodule as it does a best effort for finding a correct `location` object as it might be missing/incomplete for workers etc. But when I finished writing it there was a required dependency on the `url-parse` module as I needed to parse the location object out of an URL for blob workers. So if where to release it as npm module it would end up with recursive dependency, so I decided to keep it in the project for now.
