### ISSUE TITLE
dist folder has outdated `url-parse.js` file on npm **important**

### ISSUE THREAD

**Issue by niftylettuce** [unshiftio/url-parse#124]
hello,

can you please run `rm -rf dist && npm run browserify` and then publish the new version to npm?

the current folder on npm latest release v1.2.0 has these contents:

```sh
ls dist
url-parse.js     url-parse.min.js
```

however the `browserify` script in `package.json` only creates `url-parse.min.js` so I believe `url-parse.js` is a dev artifact

as far as I can tell, the `url-parse.js` currently in `dist/url-parse.js` on npm is outdated

perhaps when doing this you can also update the `browserify` script to publish both a minified and non-minified version with source maps as well.

once this is done this will close out issues #111 and #112

cc @3rd-Eden

**Comment by 3rd-Eden** [comment]
Do you think the referenced commit is a good solution for this problem?

1. It removes the dist folder to ensure a clean folder on every single publish
2. It creates a standalone `dist/url-parse.js`
3. minifies `dist/url-parse.js` as `dist/url-parse.min.js`
4. creates source map `dist/url-parse.min.js.map`

**Comment by niftylettuce** [comment]
looks fantastic @3rd-Eden - can you ping me once a new release is up on npm?  thanks so much, especially this quick!!! ❤️

**Comment by 3rd-Eden** [comment]
Available 1.3.0

**Comment by niftylettuce** [comment]
Thank you
