### ISSUE TITLE
lolcation breaking in browser if loc param is falsy

### ISSUE THREAD

**Issue by fvoska** [unshiftio/url-parse#136]
https://github.com/unshiftio/url-parse/blob/714747f0163e7de088568000c892e64f04e49d9a/index.js#L53

[This line](https://github.com/unshiftio/url-parse/blob/714747f0163e7de088568000c892e64f04e49d9a/index.js#L53) breaks if the code is run in browser and if `loc` value which is passed to `lolcation` is falsy. It causes `Uncaught ReferenceError: global is not defined` error. I suggest finding a different way of checking if code is running in browser or under Node.

I suggest finding a different way of checking if code is running in browser or under Node.

Some more context: This happened to me when using Swagger-UI inside Angular 6 application. It was working fine on Angular CLI project before versions 6 because Angular CLI < 6 provided a shim for `global` which was removed in 6. Temporary fix is `window.global = window;`. Relevant issue in `angular-cli`: https://github.com/angular/angular-cli/issues/8160#issuecomment-386153833

**Comment by 3rd-Eden** [comment]
That is an interesting bug because:

1. When you run node, `global` object is defined
2. When we pack the code for browser consumption, the `global` variable is introduced by browserify

So in all cases where the could should run, the `global` is variable will be specified unless it's overridden by others. So I'm not quite sure how or why this bug is manifesting.

**Comment by ahonn** [comment]
same problem. 

In the weex environment global is undefined. It causes Uncaught ReferenceError: global is not defined error.
When I change the code to `loc = loc || window.location ||  global.location || {}; `. It will work.
Please fix this problem. thanks!

**Comment by 3rd-Eden** [comment]
I released 1.4.1 with the patch of #142 @fvoska can you confirm that this fixes your problems as well?
