### ISSUE TITLE
security vulnerability notification

### ISSUE THREAD

**Issue by AndrewZamora** [unshiftio/url-parse#155]
I'm getting a security vulnerability notification from Github. Do I need to update url-parse?

![image](https://user-images.githubusercontent.com/31365406/44522531-cf5c1080-a711-11e8-8eed-bfb8c2b61a64.png)

**Comment by calamarico** [comment]
The 1.4.3 version has the problem solved, try to do:
```$ ​npm update url-parse --depth 5```

**Comment by AndrewZamora** [comment]
@calamarico Thank you the vulnerability notification went away.
