### ISSUE TITLE
setting query string doesn't support duplicate keys

### ISSUE THREAD

**Issue by Michall** [unshiftio/url-parse#163]
# Actual Result
In case of replacing query string with a new one, all the params get parsed into an object with naturally unique key/values but this is not how the query string should work - see https://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request

There is apparently no standard and multiple(duplicate) keys should be supported

# Reproduction Steps
```
a = u('https://ahoj.com/?nazdar=true&kox=true&kox=cara&kox=snih')
{ slashes: true,
  protocol: 'https:',
  hash: '',
  query: '?nazdar=true&kox=true&kox=cara&kox=snih',
  pathname: '/',
  auth: '',
  host: 'ahoj.com',
  port: '',
  hostname: 'ahoj.com',
  password: '',
  username: '',
  origin: 'https://ahoj.com',
  href: 'https://ahoj.com/?nazdar=true&kox=true&kox=cara&kox=snih' }
> a.set('query', '?nazdar=true&kox=true&kox=cara&kox=snih&neco=1')
{ slashes: true,
  protocol: 'https:',
  hash: '',
  query: { nazdar: 'true', kox: 'true', neco: '1' }, // `&kox=cara&kox=snih` missing
  pathname: '/',
  auth: '',
  host: 'ahoj.com',
  port: '',
  hostname: 'ahoj.com',
  password: '',
  username: '',
  origin: 'https://ahoj.com',
  href: 'https://ahoj.com/?nazdar=true&kox=true&neco=1' }
> a.toString()
'https://ahoj.com/?nazdar=true&kox=true&neco=1' // `&kox=cara&kox=snih` missing
```

# Expected Result
I suggest to leave query string as `string` or an array of objects(queryName: queryValue)

**Comment by lpinca** [comment]
See https://github.com/unshiftio/url-parse#usage. Use a custom parser function.

**Comment by jaredmcdonald** [comment]
this is pretty surprising behavior, any change of reopening?

```js
url('http://foo.com/').set('query', '?a=1&a=2').toString()
'http://foo.com/?a=1'
```
