### ISSUE TITLE
redirect when using window.location

### ISSUE THREAD

**Issue by knownun** [unshiftio/url-parse#172]
Hello, enjoying your library, it's very helpful.

But with the recent update, if you accidentally do this
```
new UrlParse(window.location)
```
UrlParse redirect page to this path
`%5E[/x09/x0A/x0B/x0C/x0D/x20/xA0/u1680/u180E/u2000/u2001/u2002/u2003/u2004/u2005/u2006/u2007/u2008/u2009/u200A/u202F/u205F/u3000/u2028/u2029/uFEFF]+/`

That happens because of 
![image](https://user-images.githubusercontent.com/19776951/56042386-a097b680-5d43-11e9-9985-98c35b6f3a33.png)
![image](https://user-images.githubusercontent.com/19776951/56042504-e2286180-5d43-11e9-927b-33c9ae4736b9.png)

In case `str` is a location Object

would be really helpful if you can add some kind of error, or cast address to a string

```
function Url(address, location, parser) {
  address = trimLeft(`${address}`);
```

```
function Url(address, location, parser) {
  address = trimLeft(address.toString());
```

```
function Url(address, location, parser) {
  if (typeof address !== 'string') {
    throw new Error('some text here');
  }
  address = trimLeft(address);
```

**Comment by lpinca** [comment]
I'm closing this as it should be fixed in the latest version.
