### ISSUE TITLE
Update querystringify to 2.1.1 to fix core bug with uncaught exception

### ISSUE THREAD

**Issue by niftylettuce** [unshiftio/url-parse#175]
v2.1.1 of querystringify was released which fixes an issue where it does not match Node's graceful fallback for decoding URI

https://github.com/unshiftio/querystringify/commit/30e1d1956d474a81a0d0fec9ad4f00a928b1a2d5

per Node's built-in:

> By default, the querystring.unescape() method will attempt to use the JavaScript built-in decodeURIComponent() method to decode. If that fails, a safer equivalent that does not throw on malformed URLs will be used.

https://nodejs.org/api/querystring.html#querystring_querystring_unescape_str

**Comment by niftylettuce** [comment]
Also see https://github.com/unshiftio/querystringify/issues/26

**Comment by niftylettuce** [comment]
Basically you can crash Node apps that use this package server-side in middleware by passing `%%%%` percent signs to the URL...

**Comment by 3rd-Eden** [comment]
It's worth noting that the URL-parse library is designed to allow custom query string parsers instead of the bundled querystringify. So if the primary use-cases is usage on Node.js, and want better unescape fallback for the query strings it might be an option to do this.

**Comment by niftylettuce** [comment]
@3rd-Eden could you add a deprecation notice please?  I just checked and there wasn't one there yet.

```sh
npm deprecate url-parse@"<1.4.7" "Please upgrade to v1.4.7+ as an uncaught exception bug in querystringify has been fixed and may cause a vulnerability in server-side route middleware"
```
