### ISSUE TITLE
browser location is used when baseURL set as an empty string

### ISSUE THREAD

**Issue by CxRes** [unshiftio/url-parse#177]
I would have thought `parse(url, '').toString()` would be identical to `parse(url, {}).toString()`. when the url is a relative path. The former gives an absolute url with baseURL obtained from the browser and later keeps the relative path untouched. 

Is this by design or is it a bug?

**Comment by lpinca** [comment]
It is by design, any falsy value works as if the argument was not specified.

**Comment by CxRes** [comment]
Ok! thanks for the clarification!!!!!
