### ISSUE TITLE
library not compatible with URL of nodejs and browser

### ISSUE THREAD

**Issue by adityapatadia** [unshiftio/url-parse#184]
This library is not compatible with NodeJS URL module and browser URL() module. For example, this module requires invocation of `set` method for certain variables. It also uses `query` instead of `search` used by native implementations.

Ideally this module should fallback to native methods if they are available and only use custom parsing when it's required.

I am ready to revamp this and create a PR is author agrees to merge it.

**Comment by lpinca** [comment]
It was designed to be compatible with the Node.js legacy [URL parser](https://nodejs.org/api/url.html#url_legacy_url_api) not the WHATWG URL.

**Comment by adityapatadia** [comment]
Okay then may be I will fork it and make it compatible with WHATWG parser. My use case is to use it as fallback for old browsers.

Regards,
Aditya Patadia

**Comment by adityapatadia** [comment]
It's little surprising that this library is built with client side in mind and yet supports old NodeJS parser syntax.
