### ISSUE TITLE
Email with a plus is not decoded

### ISSUE THREAD

**Issue by lc3t35** [unshiftio/url-parse#187]
I'm using Expo Linking.parse which relies on url-parse, and my url includes an email with this allowed form "x+y@xxx.com".
Decoding is incorrect as show by this additional test in PR https://github.com/unshiftio/url-parse/pull/186

**Comment by lpinca** [comment]
The third argument of the constructor accept a custom function which can be used to parse the query string. See https://github.com/unshiftio/url-parse#usage

By default https://github.com/unshiftio/querystringify is used which is limited by design.

**Comment by lc3t35** [comment]
Thank you @lpinca , I've opened an issue for expo here https://github.com/expo/expo/issues/6528, so we can see how to fix this.
Can you dig a little why querystringify replaces a + (plus sign) by space in a param ?

**Comment by lpinca** [comment]
See https://github.com/unshiftio/querystringify/issues/7

**Comment by lpinca** [comment]
I'm closing this as answered.
