### ISSUE TITLE
Password including ?

### ISSUE THREAD

**Issue by opravil-jan** [unshiftio/url-parse#191]
Hello,

we generated password including ? and when we try to parse the string we got nonsense object.
String we are trying to parse is http://example:xxx?yyy@example.com/example. We also tried to encoded it.

Thank you for help

**Comment by lpinca** [comment]
That url is not a valid url. `?` is not allowed in the userinfo subcomponent. See https://tools.ietf.org/html/rfc3986#appendix-A

**Comment by lpinca** [comment]
Special characters in the userinfo subcomponent should be encoded. I'm closing this as answered.
