### ISSUE TITLE
[BUG] the first part of pathname repeat twice after this commit: d1e7e8822f26e8a49794b757123b51386325b2b0

### ISSUE THREAD

**Issue by talentAN** [unshiftio/url-parse#198]
use this string to reshow the case. "/sections/?project=default"

**Comment by talentAN** [comment]
use this string to reshow the case. "/sections/?project=default"

**Comment by 3rd-Eden** [comment]
Could you provide more information on what exactly you are parsing including full steps to repoduce any bug that you're seeing on your end? 

```
parse('/sections/?project=default')
{ slashes: false,
  protocol: '',
  hash: '',
  query: '?project=default',
  pathname: 'sections/',
  auth: '',
  host: '',
  port: '',
  hostname: '',
  password: '',
  username: '',
  origin: 'null',
  href: 'sections/?project=default' }
```

Is what I'm seeing here.

**Comment by 3rd-Eden** [comment]
Please confirm if 1.5.1 fixes any issues you've had.

**Comment by talentAN** [comment]
> Please confirm if 1.5.1 fixes any issues you've had.

work well now~
