### ISSUE TITLE
Pathname strips out `/`

### ISSUE THREAD

**Issue by JSeligsohn** [unshiftio/url-parse#200]
Looks like in v1.5.0, pathname no longer includes the initial `/` from the url. Is that intentional? A breaking change from v1.4.7?

e.g.
url: `/yippee/abc`
1.4.7 -> path = `/yippee/abc`
1.5.0 -> path = `yippee/abc`

**Comment by 3rd-Eden** [comment]
It's a bug

**Comment by lpinca** [comment]
This is the same underlying issue of #199.

**Comment by JSeligsohn** [comment]
Okay, good to know. I'll have to revert to 1.4.7 in the meantime.

**Comment by 3rd-Eden** [comment]
Fixed in 1.5.1, thanks for reporting <3
