### ISSUE TITLE
Security issues Hostname spoofing & Open Redirect

### ISSUE THREAD

**Issue by ready-research** [unshiftio/url-parse#206]
@lpinca @3rd-Eden I have reported a security issue in huntr
https://www.huntr.dev/bounties/1625557993985-unshiftio/url-parse/ 
There are 2 attack scenarios possible for **Open Redirect** and **Hostname Spoofing(Please take a look at the last comment)**

Please validate and let us know your opinion on this. Thank you.

**Comment by lpinca** [comment]
I logged in but I can't read the report.

**Comment by JamieSlome** [comment]
@zidingz - just attaching you here for your reference.

**Comment by zidingz** [comment]
Hey @lpinca You should be able to have access to the report now. Let me know if issues persist ❤️

**Comment by lpinca** [comment]
Yes, it works now. Thanks. I've also pinged Arnout (@3rd-Eden) on Twitter.

**Comment by akazemier-godaddy** [comment]
I don't have access to the report either, but seems the same issue as reported previously on H1 about slash escaping.

**Comment by 3rd-Eden** [comment]
FML, that was my work account :joy: ANYWAYS, I can't access it on this account :joy:

**Comment by ready-research** [comment]
@zidingz can you please help on this one.
@3rd-Eden 2nd issue hostname spoofing is different from that H1 report.

**Comment by zidingz** [comment]
@3rd-Eden You should also have access now!

**Comment by lpinca** [comment]
@zidingz now I can no longer read the report :) Can we both have access or is it limited to only one maintainer?

**Comment by 3rd-Eden** [comment]
I still can't access it either.

**Comment by zidingz** [comment]
@lpinca @3rd-Eden Apologies, fixed now!

Let me know if either of you still can't view. Will be on call here until you're all set.

**Comment by 3rd-Eden** [comment]
✅ Access is working here.
