### ISSUE TITLE
lost auth with toString when password is empty

### ISSUE THREAD

**Issue by bluelovers** [unshiftio/url-parse#212]
```
{
  slashes: true,
  protocol: 'https:',
  hash: '',
  query: { ID: '12345' },
  pathname: '/tw/user',
  auth: 'user:',
  host: 'mozilla.org:8989',
  port: '8989',
  hostname: 'mozilla.org',
  password: '',
  username: '',
  origin: 'https://mozilla.org:8989',
  href: 'https://mozilla.org:8989/tw/user?ID=12345'
}
'https://mozilla.org:8989/tw/user?ID=12345'
```

**Comment by lpinca** [comment]
Did you set `auth` manually with `Url.prototype.set()`? If so that's expected because `Url.prototype.toString()` uses `username` and `password` and both are empty.

**Comment by bluelovers** [comment]
so i can't use `.set('auth', 'user:')` ? 

i have split it and use  `.set('username', )` , `.set('password', )` for make sure work as expected ?

**Comment by lpinca** [comment]
> i have split it and use  `.set('username', )` , `.set('password', )` for make sure work as expected ?

Yes.
