### ISSUE TITLE
Require keys in URL object

### ISSUE THREAD

**Issue by pranavwani** [unshiftio/url-parse#218]
**Description**
Is it possible to list the required and options keys in the URL for `url-parse` library

**Existing keys generated with empty string**
- slashes: false
- protocol: ""
- hash: ""
- query: ""
- pathname: ""
- auth: ""
- host: ""
- port: ""
- hostname: ""
- password: ""
- username: ""
- origin: "null"
- href: ""

**Comment by lpinca** [comment]
There are no required and optional keys. All properties are always preset. The library does not throw errors.

**Comment by pranavwani** [comment]
Thanks @lpinca
