### ISSUE TITLE
Incorrect handling of protocol-relative URLs in 1.5.x

### ISSUE THREAD

**Issue by krassowski** [unshiftio/url-parse#219]
```js
let url = new URL('//github.com');
url.toString()
```

results in `////github.com` but it should result in `//github.com`.

**Comment by offirgolan** [comment]
+1 to this:

<img width="814" alt="Screen Shot 2021-11-29 at 3 55 09 PM" src="https://user-images.githubusercontent.com/575938/143955614-7ada0936-9735-43e2-95f2-836aa30b8715.png">

**Comment by lpinca** [comment]
Should be fixed on master. See https://github.com/unshiftio/url-parse/commit/d9e332b3cee790b6852152b707a4e39c00945f8c. Unfortunately I can't publish a new version.

**Comment by offirgolan** [comment]
@lpinca does it make sense for the pathname to be `//github.com/foo/bar`? Shouldn't it be correctly parsed?

**Comment by lpinca** [comment]
@offirgolan that URL is invalid without a base URL. The WHATWG URL parser throws an error for it. The result is consistent with the legacy Node.js URL parser.

**Comment by offirgolan** [comment]
Got it, thanks for the clarification. Do you happen to know how we can get a new release to be published?

**Comment by lpinca** [comment]
Try to pin @3rd-Eden on Twitter.

**Comment by 3rd-Eden** [comment]
> Should be fixed on master. See [d9e332b](https://github.com/unshiftio/url-parse/commit/d9e332b3cee790b6852152b707a4e39c00945f8c). Unfortunately I can't publish a new version.

I need to figure a way to get stuff autopublished.

**Comment by 3rd-Eden** [comment]
Closing this as I managed to publish this from my windows machine. 

Note to self: Using linux commands in publish steps is a bad practice.

**Comment by krassowski** [comment]
Thank you. It still looks a bit weird because `new URL('://github.com')` is missing hostname, host and has a bit strange pathname when compared to `new URL('https://github.com')`:

```js
> new URL('//github.com')
{
  slashes: true,
  protocol: '',
  hash: '',
  query: '',
  pathname: '//github.com',
  auth: '',
  host: '',
  port: '',
  hostname: '',
  password: '',
  username: '',
  origin: 'null',
  href: '//github.com'
}
```

compare to:

```js
> new URL('https://github.com')
{
  slashes: true,
  protocol: 'https:',
  hash: '',
  query: '',
  pathname: '/',
  auth: '',
  host: 'github.com',
  port: '',
  hostname: 'github.com',
  password: '',
  username: '',
  origin: 'https://github.com',
  href: 'https://github.com/'
}
```

I would have expected that the only differences would be:
- missing `https` in `href` and `origin`, and
- empty `protocol`

but isntead there a difference in `pathname`, missing `hostname`, null `origin` and lack of trailing slash for `href`.

Is this intended?

**Comment by lpinca** [comment]
@krassowski yes this is expected, see @offirgolan comment above. `//github.com` is an invalid URL without a base URL. The WHATWG URL parser throw an error without a base URL. This behavior is to be consistent with the legacy Node.js URL parser.
