### ISSUE TITLE
1.5.4 breaks set() method for us

### ISSUE THREAD

**Issue by byumark** [unshiftio/url-parse#222]
We are doing something like this:

```
const parse = require('url-parse')

let parsed = parse(destination)
parsed.set('username', undefined)
parsed.set('password', undefined)

console.log(parsed.href)
```
When passed this as the destination:
`http://user:pass@host.com`

1.5.3 and before logs this:
`http://host.com`

1.5.4 logs this:
`http://undefined:undefined@host.com`

It works with an empty string but no longer works when setting to `undefined`. I think this commit may have affected this behavior: https://github.com/unshiftio/url-parse/commit/53d4d6dfd1ec24f5747271c6f2e86ffa6959b22b

**Comment by lpinca** [comment]
I see the breaking change in a patch release, sorry, but I think that this is reasonable. Using `undefined` to unset `url.username` and `url.password` was undocumented behavior.
