### ISSUE TITLE
relative urls without leading slash are not parsed properly

### ISSUE THREAD

**Issue by guiweber** [unshiftio/url-parse#26]
For example:
```javascript
  url = new urlparse("a/7z1514-x64.msi", "http://www.7-zip.org/download.html");
  console.log(url.hostname);
```
prints "a"
while
```javascript
  url = new urlparse("/a/7z1514-x64.msi", "http://www.7-zip.org/download.html");
  console.log(url.hostname);
```
prints "www.7-zip.org"

**Comment by 3rd-Eden** [comment]
Well isn't the output correct as in your first example `a` really is valid hostname.

**Comment by guiweber** [comment]
Well, not in this context. The link in the first example is resolved as ""http://www.7-zip.org/a/7z1514-x64.msi" on the webpage ([try it for yourself here](http://www.7-zip.org/download.html)), so I would expect url-parse to give me "www.7-zip.org" as host name given the base url provided.

If a base url is provided, a url starting with a segment with no leading slash is considered relative to the current path (in contrast to a url starting with a slash which is relative to the web root):

[From wikipedia](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Examples_of_URI_references):

> /relative/URI/with/absolute/path/to/resource.txt
relative/path/to/resource.txt

[From Stackoverflow](https://stackoverflow.com/questions/2005079/absolute-vs-relative-urls):
> images/example.png
This is also a relative URL although a bit different than the previous one. This URL is relative to the current path. What this means is that it will resolve to different paths depending on where you are in the site.

Also, `a`  would be an ambiguous host name as it doesn't include the top level domain. Is it worth supporting those? In all cases I can imagine, a useful host name would have the top level domain, so at least two parts separated by a dot.

In any case, if a base url is provided it should be seen as a relative url.

**Comment by jcrugzz** [comment]
@guiweber Why wouldn't you switch the order of the arguments here so that the proper URL with the domain is recognized as the address. You can see how this gets interpreted [here](https://github.com/unshiftio/url-parse/blob/master/index.js#L61-L65). Or am i missing something?

**Comment by guiweber** [comment]
So lets say I'm analyzing links on the http://www.7-zip.org/download.html page and want to check if the links point to the current domain or to another domain.

my code would look like this:
```javascript
const urlparse = require('url-parse');

function isSameHost(link, base){
  u1 = new urlparse(link, base);
  u2 = new urlparse(base);
  return (u1.hostname == u2.hostname);
}

console.log(isSameHost("a/7z1514-x64.msi", "http://www.7-zip.org/download.html"));
console.log(isSameHost("/a/7z1514-x64.msi", "http://www.7-zip.org/download.html"));
console.log(isSameHost("http://sourceforge.net/projects/sevenzip/files/", "http://www.7-zip.org/download.html"));
```
This returns:
false    ==> expected true
true     ==> ok
false   ==> ok

If I were to simply reverse the order of the `base` and `link` arguments, then the first address would be parsed and I would always get "www.7-zip.org" as host name (which is not right for links that are not relative):

```javascript
const urlparse = require('url-parse');

function isSameHost(link, base){
  u1 = new urlparse(base, link);
  u2 = new urlparse(base);
  return (u1.hostname == u2.hostname);
}

console.log(isSameHost("a/7z1514-x64.msi", "http://www.7-zip.org/download.html"));
console.log(isSameHost("/a/7z1514-x64.msi", "http://www.7-zip.org/download.html"));
console.log(isSameHost("http://sourceforge.net/projects/sevenzip/files/", "http://www.7-zip.org/download.html"));
```
This returns:
true
true
true

this won't work as it will give `true` for all links on a web page such as "http://sourceforge.net/projects/sevenzip/files/".

**Comment by guiweber** [comment]
p.s. the issue is not only about hostnames. If you want to resolve a relative link, url-parse is supposed to combine the `url` and `baseURL` argument. However, for relative links without leading slashes, it doesn't work:

```javascript
const urlparse = require('url-parse');
u = new urlparse("relative/path/to/resource.html", "http://mydomain.com/current/page.html");
console.log(u.href);
```

This prints "http://relative/path/to/resource.html"
but it should print "http://mydomain.com/current/relative/path/to/resource.html"

**Comment by lpinca** [comment]
#39 should fix this issue.
