### ISSUE TITLE
Carefully crafted url can give the wrong hostname

### ISSUE THREAD

**Issue by holm** [unshiftio/url-parse#29]
This was reported to us by a security researcher.

```js
const URL = require('url-parse');

const url = new URL('http://attacker.com\@google.com');

console.log(url.hostname);
```

This will output `google.com`, however if you open the url in Chrome it will end up on `attacker.com`.

**Comment by lpinca** [comment]
It's not an excuse but node built-in url parser has the same behavior:

Node:

```js
url.parse('http://attacker.com\@google.com')
Url {
  protocol: 'http:',
  slashes: true,
  auth: 'attacker.com',
  host: 'google.com',
  port: null,
  hostname: 'google.com',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://attacker.com@google.com/'
}
```

url-parse:

```js
new URL('http://attacker.com\@google.com')
URL {
  protocol: 'http:',
  slashes: true,
  hash: '',
  query: '',
  pathname: '',
  auth: 'attacker.com',
  host: 'google.com',
  port: '',
  hostname: 'google.com',
  password: '',
  username: 'attacker.com',
  href: 'http://attacker.com@google.com'
}
```

**Comment by 3rd-Eden** [comment]
Which is also how browsers handle it. 

```js
a = document.createElement('a');
a.href = 'http://attacker.com\@google.com';
'protocol,hash,auth,host,hostname,username,href'.split(',').forEach(function(prop) { 
  console.log(prop +':', a[prop]); 
});

// protocol: http:
// hash: 
// auth: undefined
// host: google.com
// hostname: google.com
// username: attacker.com
// href: http://attacker.com@google.com/
```

**Comment by 3rd-Eden** [comment]
So from an URL parsing perspective, it all seems that we're handling this correctly.

**Comment by lpinca** [comment]
The URL interface in the browser acts differently:
```js
new URL('http://attacker.com\@google.com');
URL {
  href: "http://attacker%2Ecom@google.com/",
  origin: "http://google.com",
  protocol: "http:",
  username: "attacker%2Ecom",
  password: "",
  host: "google.com",
  hostname: "google.com",
  port: "",
  pathname: "/",
  search: ""
}
```

**Comment by 3rd-Eden** [comment]
Python on the other hand handles it exactly the same:

```
>>> from urlparse import urlparse
>>> o = urlparse('http://attacker.com\@google.com')
>>> o.hostname
'google.com'
>>> o.username
'attacker.com\\'
````

**Comment by 3rd-Eden** [comment]
@lpinca Isn't that exactly the same result as we and node are doing?

**Comment by lpinca** [comment]
Yeah it is :smile:, edited comment.

**Comment by holm** [comment]
Seems like this is more of a Chrome navbar issue then. I will try to report it to them.

**Comment by 3rd-Eden** [comment]
I guess the only reassuring thing here is that URL is correctly fixed after it's parsed as the `\` that prefixes the `@` is removed from the resulting `href`.

@holm It doesn't only affect Chrome but all WebKit browsers it seems.

**Comment by holm** [comment]
Filed a Chromium issue, hopefully that should bring some clarity: https://bugs.chromium.org/p/chromium/issues/detail?id=605452

**Comment by holm** [comment]
The chromium team came back and says it is a WontFix. They didn't really give any justification, but it had been reported previously, and also been marked as WontFix.

IE seems to behave the same way as Chrome, while Firefox handles it differently. Too bad for web developers :)

**Comment by lpinca** [comment]
Luckily the browsers show a warning message, but it is still weird that the URL is parsed differently in the URL bar :confused: .
