### ISSUE TITLE
Setting `host` without port does not set up hostname.

### ISSUE THREAD

**Issue by forstermatth** [unshiftio/url-parse#30]
I'm not sure if this is a bug or expected but I figured I'd post it.

-----

I've run into a weird issue where setting the host without a port does not set the hostname. It looks like the `hostname` doesn't get updated when the URL given to `.set('host' url)` doesn't include a port.

To quote the docs:
> When you set a new host you want the same value to be applied to port if has a different port number, hostname so it has a correct name again and href so you have a complete URL.

Example: https://tonicdev.com/forstermatth/5744707784453d13005060c3

**Comment by lpinca** [comment]
The behavior you are describing is expected with the current [code](https://github.com/unshiftio/url-parse/blob/ea94dd5ba21bfa417746cbddf9e5239930c4a66a/index.js#L214-L218) but it seems wrong to me.
I think this is the correct behavior when `port` is missing:
```js
url.hostname = value;
url.port = '';
```

**Comment by forstermatth** [comment]
Looking at the behavior of the other options, I agree.

```js
else if ('host' === part) {
  url[part] = value;
  value = value.split(':');
  url.hostname = value[0]; // will be empty string if value = `:port`
  url.port = value[1] || ''; // set to empty string if undefined for value = `hostname`
} ...
```

This would bring case 4 of the example into line with the rest:

```
var parsed4 = parse('http://ip:3006/endpoint'); // port incl.
parsed4.set('hostname', '0.0.0.0'); // hostname is set
parsed4.set('host', '0.0.0.0'); // hostname is set, port is unset
```

**Comment by lpinca** [comment]
I would not handle cases where `host` is invalid like `:3000` as you are using it incorrectly.
For the same reason I would assume that at least `hostname` is provided.
Also we should handle IPv6 hosts like `[::1]:3000`. Something like this should work:
```diff
diff --git a/index.js b/index.js
index 598b1c4..855a205 100644
--- a/index.js
+++ b/index.js
@@ -211,10 +211,13 @@ URL.prototype.set = function set(part, value, fn) {
   } else if ('host' === part) {
     url[part] = value;
 
-    if (/\:\d+/.test(value)) {
+    if (/:\d+$/.test(value)) {
       value = value.split(':');
-      url.hostname = value[0];
-      url.port = value[1];
+      url.hostname = value.slice(0, -1).join(':');
+      url.port = value[value.length - 1];
+    } else {
+      url.hostname = value;
+      url.port = '';
     }
   } else if ('protocol' === part) {
     url.protocol = value;
```

**Comment by forstermatth** [comment]
I hadn't even considered v6, I see why the regex is needed now. You're example looks great, I like the use of `.pop()`.

**Comment by lpinca** [comment]
If you reopen and update your pr I'll merge it.
