### ISSUE TITLE
lolcation.js?

### ISSUE THREAD

**Issue by olegstepura** [unshiftio/url-parse#34]
lol =) This is truly lolcation. Don't you want to rename this or did you do this intentionally?

FIY: noticed this when building my app with webpack. Some dependency used your package =)

**Comment by olegstepura** [comment]
Sorry, seems like it already was here #10
So after half a year didn't you decide to rename the file?

**Comment by 3rd-Eden** [comment]
@olegstepura The filename still makes me smile when I see it, once that stops happening i will rename it. Having fun while programming is one of the most important things out there and it can be these little things that make it worth it. I can see it can be a bit confusing for people but that doesn't outweigh the smile that it puts on people's faces ;-)

**Comment by olegstepura** [comment]
:+1:  @3rd-Eden absolutely right! Without this name I would never know you! =) Let it be so!
