### ISSUE TITLE
Get method to read query parameter

### ISSUE THREAD

**Issue by drveresh** [unshiftio/url-parse#35]
Similar to set() method, can you please add get() method as well so that it helps reading params from the URL

**Comment by iamtheib** [comment]
I believe the params you want access to are already exposed on the URL instance. Take a look at the [Usage](https://github.com/unshiftio/url-parse#usage) section of the README.

If that is not what you're asking for, could you give a sample code of what you want?

**Comment by 3rd-Eden** [comment]
If you parse the URL you already get an object returned with a `query` as property, which is the parsed query param. So you can just do (please note the second `true` argument)

```js
var url = urlparse('www.google.com?query=param', true);
console.log(url.query);
```
