### ISSUE TITLE
Sauce Labs Builds Failing

### ISSUE THREAD

**Issue by nf071590** [unshiftio/url-parse#40]
Hello, 

I was interested in using this package in my web app project but it's not clear to me about the different browsers it supports.

Can you help me with this?

Best,

Nick

**Comment by 3rd-Eden** [comment]
Yeah, sauce is acting up but it runs against: https://github.com/unshiftio/url-parse/blob/master/.zuul.yml#L3-L18 for sanity checks but in reality any JS environment that supports that loops and regular expressions should work.

**Comment by lpinca** [comment]
@nf071590 zuul + localtunnel.me don't work very well lately, we should find a better way to run cross browser testing.
Anyway the latest CI run was successful, see https://saucelabs.com/u/url-parse.
I close this now, please reopen or comment if you feel this does not answer your question.
