### ISSUE TITLE
Please add this typings to your git so that it can stay in sync with the code

### ISSUE THREAD

**Issue by ddehghan** [unshiftio/url-parse#46]
Thanks for the great work.

Here is the typings:
https://gist.github.com/nertzy/d3110cae677913c476e8b4895eeaf412

**Comment by 3rd-Eden** [comment]
Would adding it here be more favorable than adding it to https://github.com/DefinitelyTyped/DefinitelyTyped ?

**Comment by theandrewlane** [comment]
Thanks @ddehghan!

For all you lazy people 😄:
```
npm i -g typings
```

```
typings install url-parse=https://gist.githubusercontent.com/nertzy/d3110cae677913c476e8b4895eeaf412/raw/7186912fcc60d04f7bb7c67c8cbb2f4afa270218/url-parse.d.ts --global --save
```

**Comment by ncknuna** [comment]
Maybe I'm missing something obvious, but is there an equivalent syntax for using this with npm and @types? If there isn't, can we try to add these typings to this repo or add them to @types?

**Comment by todthomson** [comment]
@ddehghan here's a rough guide

**Comment by lpinca** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20233
