### ISSUE TITLE
Parsing defaults to current browser location

### ISSUE THREAD

**Issue by LINKIWI** [unshiftio/url-parse#64]
Is this intended? When running in a browser, calling `url-parse` on some strings will automatically default the host name and port to the current browser location. This is very confusing.

For example, my internal DNS resolves the name `host`. In a browser environment, on a page whose URL is `http://localhost:5000`:

```js
const urlParse = require('url-parse');
const parsed = urlParse('host');
console.log(parsed.host);  // localhost:5000
console.log(pathname);  // /host
```

For a more "traditional" URL, in the same browser, at the same window URL:

```js
const urlParse = require('url-parse');
const parsed = urlParse('https://google.com');
console.log(parsed.host);  // google.com
```

Why does the library assume the current window URL is the base URL, and treats the input string as a relative path? The URL I am attempting to parse is not in any way related to the current window location.

**Comment by LINKIWI** [comment]
For what it's worth, in a browser environment, if you call `urlParse('');` it will also parse the current browser location.

**Comment by LINKIWI** [comment]
Seems like the culprit is the default to `global.location` here: https://github.com/unshiftio/url-parse/blob/master/index.js#L53

**Comment by lpinca** [comment]
This is done on purpose

![screen shot 2017-06-12 at 08 05 34](https://user-images.githubusercontent.com/1443911/27021031-f853de70-4f45-11e7-9f06-51705d515d9d.png)

You can use a different base URL though.

```js
const urlParse = require('url-parse');
const parsed = urlParse('host', {});

assert.deepStrictEqual(parsed, {
  slashes: false,
  protocol: '',
  hash: '',
  query: '',
  pathname: 'host',
  auth: '',
  host: '',
  port: '',
  hostname: '',
  password: '',
  username: '',
  origin: 'null',
  href: 'host'
});
```

**Comment by LINKIWI** [comment]
Thanks @lpinca - would you accept a PR documenting this more explicitly in the README?

I'll close this issue as it stands now.

**Comment by lpinca** [comment]
Sure, PRs are always welcome.
