### ISSUE TITLE
Error parse query Array

### ISSUE THREAD

**Issue by Fi1osof** [unshiftio/url-parse#70]
Good day!

new URL('http://localhost/?blog[]=1&blog[]=2&blog[]=3');
result href: "http://localhost/?blog[]=1&blog[]=2&blog[]=3"

new URL('http://localhost/?blog[]=1&blog[]=2&blog[]=3', true)
result href: "http://localhost/?blog%5B%5D=3"
**Error**: got only last value;

http://joxi.ru/MAj0VK9h4Ogydm

react-router browserHistory do parse this correct;

**Comment by lpinca** [comment]
Hi,
internally `url-parse` uses [`querystringify`](https://github.com/unshiftio/querystringify) which is super simple and only supports basic query strings.

You can, however, specify a custom query string parser:

```js
var URL = require('url-parse');
var qs = require('qs');

var url = new URL('http://localhost/?blog[]=1&blog[]=2&blog[]=3', qs.parse);
```

**Comment by Fi1osof** [comment]
OK. Thanks!
