### ISSUE TITLE
How is the dist folder built?

### ISSUE THREAD

**Issue by mcpherson-sa** [unshiftio/url-parse#82]
I am trying to understand the source. When I install the module using npm there is dist folder which isn't included in the git repo. Am assuming the files in dist are generated somehow but I compared index.js to url-parse.js and they are some similarities they are quite different so I can't see how url-parse.js would be generated from index.js.

**Comment by saki7** [comment]
@mcpherson-sa see the `prepublishOnly` and `browserify` entries on package.json

**Comment by mcpherson-sa** [comment]
I saw these, so I took out the uglify step and the code that is generated looks like the contents of index.js but it is quite different from the url-parse.js file that gets installed by npm. For example the packaged url-parse.js includes are long regex which is not included in index.js, and although the two files have similar function names the contents are quite different.

**Comment by mcpherson-sa** [comment]
From what I can figure out url-parse.min.js is build from index.js which makes sense as that is generated by the browserify script in package.json but url-parse.js seems to be based on something else and there doesn't seem to be anything in package.json to build url-parse.js.

**Comment by mcpherson-sa** [comment]
I think I know what is happening, I checked out a old version of the code and index.js it looks more  like the packaged version url-parse.js so I think dist/url-parse.js is an old version of the library which hasn't been cleaned up.

**Comment by lpinca** [comment]
@mcpherson-sa yes you are correct that is a leftover that has been accidentally published.
