### ISSUE TITLE
`pathname` === '' ?

### ISSUE THREAD

**Issue by mantou132** [unshiftio/url-parse#96]
Hope to provide a parameter to be compatible Web URL [https://developer.mozilla.org/en-US/docs/Web/API/URL]()

new URL('http://www.example.com').pathname === '/'
==> true

**Comment by nigel-codaio** [comment]
FWIW, this change was made in https://github.com/unshiftio/url-parse/pull/197 and has broken a bunch of our code assumptions.

**Comment by lpinca** [comment]
I'm closing this as behavior is now consistent with the browser and Node.js WHATWG URL parser.
