### ISSUE TITLE
Add static method `resolve`

### ISSUE THREAD

**Issue by CodeDaraW** [unshiftio/url-parse#97]
I have lots of relative URLs needed to be resolved as abstract URLs, but just create an instance for each URL like `(new URL(relative, base)).href` may be too expensive.

At the moment, the `url-parse` already has a private method `resolve`, can we make it public as a static method just like [URL.resolve](https://nodejs.org/docs/latest/api/url.html#url_url_resolve_from_to) in Node?

If you accept it, I can help create a new PR.

Thanks for the project, it really helps me a lot.

**Comment by lpinca** [comment]
The Node.js `url.resolve()` creates an `Url` instance for the [`source`](https://github.com/nodejs/node/blob/bf6ce47259ebfe9f6349c223cc1735726aee062d/lib/url.js#L653) and [`relative`](https://github.com/nodejs/node/blob/bf6ce47259ebfe9f6349c223cc1735726aee062d/lib/url.js#L657) arguments, so it's not different from `url-parse`. It's just syntactic sugar.

I think that using

```js
const parse = require('url-parse');
const { href: resolved } = parse(relative, base);
```

is not that bad.

**Comment by CodeDaraW** [comment]
Thanks for your explanation.

The cost of creating new instances may not affect much after rethinking, so I will keep using like this:
``` JavaScript
import URL from 'url-parse';

const href = (new URL(relative, base)).href;
```
